static const char black[]       = "#2A303C"; 
static const char white[]       = "#eceff4";
static const char gray2[]       = "#4c566a"; // darker
static const char gray4[]       = "#D8DEE9"; // off-white
static const char blue[]        = "#81A1C1"; 
static const char blue2[]       = "#5e81ac"; // darker
static const char green[]       = "#89b482";
static const char red[]         = "#d57780";
static const char orange[]      = "#caaa6a";
static const char yellow[]      = "#EBCB8B";
static const char pink[]        = "#e39a83";
static const char col_borderbar[]  = "#2A303C"; // inner border
